### ISSUE TITLE
How to download it

### ISSUE THREAD

**Issue by AshIsAwesome123** [EZForever/UDPWiiHook#8]
IM SO FUCKING CONFUSED HOW TO DOWNLOAD IT????

**Comment by EZForever** [comment]
This project is long unmaintained, and, given your attitude, I don't think you'll find this project useful (or rather, *usable*).

However if you still want to try, some pre-built releases can be found on [the "Releases" page](https://github.com/EZForever/UDPWiiHook/releases). Click on "Assets".

**Comment by EZForever** [comment]
Closing as is not a valid issue.
